### ISSUE TITLE
无法登陆

### ISSUE THREAD

**Issue by lulululbj** [TonnyL/Mango#10]
点击开始吧之后，跳转到系统自带 Chrome 进行授权，点击 Authorize 之后进入我填写的回调地址，然后就没有然后了。。

**Comment by TonnyL** [comment]
嗨, @lulululbj 

机器型号是什么? 是三星的系统吗? 貌似在三星的系统上会有这个问题, AOSP 正常.

**Comment by lulululbj** [comment]
是的，三星手机

**Comment by TonnyL** [comment]
暂时还不知道是啥问题 😂, 你是在 Google play 上下载安装的还是跑的代码?

**Comment by lulululbj** [comment]
跑的代码，可以修改成 内部 webview 访问。我之前做 github 登陆就这么做的

**Comment by TonnyL** [comment]
这三星...   诡异,   不过这个项目不打算维护了, 因为 dribbble 要关闭 API 了😭

**Comment by lulululbj** [comment]
Thanks. 冲着 kotlin + MVP 来的。代码结构和风格很好，准备搬过来自己用。😭

**Comment by TonnyL** [comment]
谢谢, 推荐你一个更好的, [Protein](https://github.com/gejiaheng/Protein)(Java)  和 官方的 [Android Architecture Blueprints](https://github.com/googlesamples/android-architecture)😄

**Comment by TonnyL** [comment]
嗨 @lulululbj 
如果没有其他问题的话, 我就要关闭这个 issue 了. 如有疑问, 请重开这个 issue 或直接创建一个新的.

**Comment by lulululbj** [comment]
OK，谢谢了

**Comment by TonnyL** [comment]
不客气😄
