### ISSUE TITLE
account

### ISSUE THREAD

**Issue by guxiaonian** [TonnyL/Mango#11]
There is no test account here, can you give me an account?

**Comment by TonnyL** [comment]
Hi, @guxiaonian 

Just go to [Dribbble](https://dribbble.com/) and sign up a new account, please.

**Comment by guxiaonian** [comment]
but the URL is wrong,the title "Sorry,you sent a bad request(400)"

**Comment by TonnyL** [comment]
Are you using a Samsung device?

**Comment by TonnyL** [comment]
Any problem? I will edit last comment to remove my account and password. 😄

**Comment by guxiaonian** [comment]
i think the api is overtime ,so I look look the java, no play it on a device.

**Comment by TonnyL** [comment]
OK, I close the issue then. If you have any other problems, don't hesitate to reopen the issue or just open another one. 😄
