### ISSUE TITLE
Please update Api to v2

### ISSUE THREAD

**Issue by alfredchan3** [TonnyL/Mango#12]

**Comment by TonnyL** [comment]
Hi, @alfredchan3 

Which API do you mean? Dribbble or any other?

**Comment by TonnyL** [comment]
Hi, @alfredchan3 
Sorry I mixed up. The Dribbble API V2 limits a lot of actions. So I do **NOT** have any plans to migrate. You could check the doc of API V2 for details. 

Here is a part of content that I copied from Dribbble API [Change Log](http://developer.dribbble.com/changes/):

> We’ve refocused v2 on providing a Publishing API. API v2 expands developers’ options for building applications and integrations that allow designers to publish their work on Dribbble, but removes the endpoints that offer aggregated streams of shots. We will continue to provide an endpoint to designers to list their own shots. Developers should plan to migrate their applications away from endpoints scheduled for removal. Developers should plan to migrate their applications away from the v1 endpoints scheduled for removal.

That means developers can **NOT** get any feeds of shot anymore, including the Popular, the Following, the Recent and the Debuts. And you are not able to get other uses' published or liked shots.

**Comment by alfredchan3** [comment]
thx a lot.. @TonnyL

**Comment by TonnyL** [comment]
You are welcome.😄
