### ISSUE TITLE
Dribbble Access Token

### ISSUE THREAD

**Issue by bluemix** [TonnyL/Mango#14]
Hello dear,
I far as it could be, Client Access Token should be below the Client Secret, 
but it is now showing.

<img width="689" alt="screen shot 2018-03-22 at 20 15 28" src="https://user-images.githubusercontent.com/3332274/37786844-b69fee76-2e0e-11e8-9bfa-4ae28ed0dfec.png">

so, how to get it?

**Comment by TonnyL** [comment]
Hi, @bluemix, 

Dribbble will close the api v1 in the near future. See this issue: https://github.com/TonnyL/Mango/issues/12

**Comment by bluemix** [comment]
so, how new users can pass the login screen?

**Comment by TonnyL** [comment]
The dribbble api v1 will be deprecated on someday of May, sorry  that I can't remember the exact date, that means most third-party apps will lose their functions. If you want to develop a new dribbble application, I don't recommend you do that.

**Comment by bluemix** [comment]
do you mean I can't run this app correctly?

**Comment by TonnyL** [comment]
If you just want to build the project and run the mango application, you could download the project first and check the commit history, you will find the mango.properties file. Copy it  and paste it to the root dir just like the README.md says.

**Comment by bluemix** [comment]
Ah, Ok.
thanks :)

**Comment by TonnyL** [comment]
You are welcome. Feel free to comment if get any new problems.

**Comment by bluemix** [comment]
bty, I didn't find the mango.properties file in the commits history.
and what about new users want to use this app?

**Comment by TonnyL** [comment]
You could find the file in initial commit (first commit). For normal user, they could use the app until May if they have dribbble accounts.

**Comment by bluemix** [comment]
that is the first commit, I don't see the `mango.properties` file
![screen shot 2018-03-23 at 14 50 57](https://user-images.githubusercontent.com/3332274/37827717-ab40f296-2ea9-11e8-9c61-84e58c257b8c.png)

**Comment by TonnyL** [comment]
Ok, I will paste it right here tomorrow because I am not in front computer right now.

**Comment by TonnyL** [comment]
Hi, @bluemix 

Here it is:

```java
CLIENT_ID=880e6d00af514d4c2046b3ea49c82397ddc0e81f3239dabd5a79a91dc9003aeb
CLIENT_SECRET=da035b73967362330aea7fc9cc9ce66a6e945b87c34e3a7cbf1a871e4bf13c61
CLIENT_ACCESS_TOKEN=2345496566b85d63b207200b6fa64a9de8dbe4654e9883ab67b477e47aa5230a
```

The keys are only for developing, so do not use them for other ways.

**Comment by bluemix** [comment]
OK, my dear,
thanks a lot 👍

**Comment by TonnyL** [comment]
Hi, @bluemix 

Any new problem? If the answer is negative, I will remove the private keys from this issue and close it.

**Comment by bluemix** [comment]
yes, Ive tested those and worked on them.
thanks again.

**Comment by TonnyL** [comment]
Then I will close this issue. Feel free to reopen it or just open another one if you get any new problem. Happy coding 😉!
