### ISSUE TITLE
HTTP 401 after logging

### ISSUE THREAD

**Issue by MyNameIsTroll** [TonnyL/Mango#17]
Hello,
after installing the application, and after logging into my dribbble account with (get started) I get the message "http 401", I can't do anything.

I am under Android 8.1.0 (samsung galaxy S5) Rom: LineageOS

![d2911a9d61c441f3](https://user-images.githubusercontent.com/31790025/45220046-33074180-b2ad-11e8-927a-60f7a9318748.png)

**Comment by TonnyL** [comment]
Hi, @MyNameIsTroll 

Check this issue for more info: https://github.com/TonnyL/Mango/issues/12

**Comment by MyNameIsTroll** [comment]
@TonnyL , thank you for your answer. :)

**Comment by TonnyL** [comment]
That's not a big deal. Then I will close this issue now. If you get any new issue, welcome to reopen this or file a new one. Happy coding 😉.
