### ISSUE TITLE
怎么获取VERIFICATION TOKEN

### ISSUE THREAD

**Issue by quanlinzxh** [TonnyL/Mango#18]
我注册的时候只生成了CLIENT ID,CLIENT SECRET,没有VERIFICATION TOKEN

**Comment by TonnyL** [comment]
http://developer.dribbble.com/changes/

**Comment by TonnyL** [comment]
如果没有其他问题，我要关掉这个 issue 了。欢迎随时重新打开或者直接新开一个 issue 😉

**Comment by quanlinzxh** [comment]
看完你发的文档我还是不知道如何获取VERIFICATION TOKEN,是不是在这个页面获取的https://developer.dribbble.com/v2/oauth/#web-application-flow

**Comment by TonnyL** [comment]
API v2 取消了吧，如果你打算实现 mango 的这个效果，现在 dribbble 的 API v2 应该是没有办法实现的，很多 API 都已经不提供了。

**Comment by quanlinzxh** [comment]
好的,知道了,谢谢

**Comment by TonnyL** [comment]
客气了
