### ISSUE TITLE
Replace kotlin synthetic with viewBinding

### ISSUE THREAD

**Issue by osualaFC** [TonnyL/Mango#20]
Read an article that kotlin synthetic will be deprecated in the next kotlin release, I will like to integrate viewBinding into this project.
Reference:https://www.reddit.com/r/androiddev/comments/jetvoa/kotlinandroidextensions_plugin_will_be_deprecated/?utm_source=share&utm_medium=ios_app&utm_name=iossmf

**Comment by TonnyL** [comment]
Very glad to know that kotlin synthetic will be deprecated and look forward to review your pr 😀

**Comment by osualaFC** [comment]
checkout my pull request

**Comment by TonnyL** [comment]
Thx!
