### ISSUE TITLE
导入报错呀.....

### ISSUE THREAD

**Issue by cjcj125125** [TonnyL/Mango#7]
classpath 'com.android.tools.build:gradle:3.0.0-rc1'   这个导入不进去呀，另外repositories 中的 google()也找不到呀  、楼主你是不是翻墙了

**Comment by TonnyL** [comment]
hi, @cjcj125125 

The project requests Android Studio 3.0 and up. You need to update your Android Studio to **3.0.0-rc1** version( **the latest is 3.0.0-rc2**). Or you could downgrade the gradle version to your owns.

**Comment by TonnyL** [comment]
Hi, @cjcj125125 
If you have solved the problem, I'll close the issue.😉
